#!/bin/sh

brightness_file=$HOME/.config/sway/scripts/brightness_value

brightness_percent=$(cat $brightness_file)

new_brightness=$(($brightness_percent + 10))

if [ "$new_brightness" -ge "100" ]; then
	brightnessctl s 100%
	echo 100 > $brightness_file
else
	brightnessctl s $new_brightness%
	echo $new_brightness > $brightness_file
fi
