#!/bin/bash
# requires pamixer package to read out volume

volume=$(pamixer --get-volume)

if [[ $(( $volume + 10 )) -ge 100 ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ 100%
	volume=100
else
	pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ +10%
	volume=$(($volume + 10))
fi
