#! /bin/sh
if mkdir /tmp/backScript 2> /dev/null; then
	sleep 2s
	wal -i "$HOME/Pictures/wallpapers"
	sleep 3s
	pulseaudio &
	udiskie -N &
	export QT_QPA_PLATFORMTHEME="qt5ct"
	while :
	do
		sleep 10m
		wal -i "$HOME/Pictures/wallpapers"
	done
fi
